# Generated by Django 5.2.8 on 2025-11-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('price', models.FloatField()),
                ('body_design', models.CharField(max_length=100)),
                ('drive_type', models.CharField(max_length=100)),
                ('fuel_type', models.CharField(max_length=100)),
                ('seats', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('mileage', models.FloatField()),
            ],
        ),
    ]
